on:
  pull_request:
  push:
    branches:
      - main
      - master
      - github-actions

jobs:
  build-linux:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amd64
            package: ""
            cc: "gcc"
          - name: armv7
            package: "-arm-linux-gnueabihf"
            cc: "arm-linux-gnueabihf-gcc"
          - name: aarch64
            package: "-aarch64-linux-gnu"
            cc: "aarch64-linux-gnu-gcc"
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y make libsdl2-image-dev gcc-10${{ matrix.package }}
      - name: Build
        env:
          CFLAGS: "-I/usr/include/x86_64-linux-gnu/SDL2"
        run: make -C src -j $(nproc) all CC=${{ matrix.cc }}-10  
      - name: List
        run: ls -l

