on:
  pull_request:
  push:
    branches:
      - main
      - master
      - github-actions

jobs:
  build-linux:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc-version: [10]
        include:
          - name: x86_64
            package: ""
            cc: "gcc"
          - name: armv7
            package: "-arm-linux-gnueabihf"
            cc: "arm-linux-gnueabihf-gcc"
          - name: aarch64-linux-gnu
            package: "-aarch64-linux-gnu"
            cc: "aarch64-linux-gnu-gcc"
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y make libsdl2-image-dev gcc-${{ matrix.gcc-version }}${{ matrix.package }}
      - name: Build
        run: make -C src -j $(nproc) all CC=${{ matrix.cc }}-${{ matrix.gcc-version }}
      - name: List
        run: ls -l

